#!/usr/bin/env python3
"""Condense the vendored C++ Core Guidelines into one file per section.

Each rule keeps its id, its title and its Reason text, or its lead text up to the first heading
when it has no Reason heading. Examples, notes, exceptions and enforcement text are dropped. A rule whose reason is missing, empty or only "???" is a stub and is dropped.
The output is deterministic: a rerun on the same input writes byte-identical files.
"""

import argparse
import pathlib
import re
import sys

ROOT = pathlib.Path(__file__).resolve().parent.parent
BASE = ROOT / "plugins" / "cure" / "knowledge" / "cpp-core-guidelines"

SECTIONS = [
    "P", "I", "F", "C", "Enum", "R", "ES", "Per", "CP", "E", "Con", "T", "CPL", "SF", "SL", "A",
]

SECTION_HEADING = re.compile(r'^# <a name="[^"]*"></a>([A-Za-z]+): (.+)$')
RULE_HEADING = re.compile(r'^### <a name="[^"]*"></a>\s*([A-Za-z]+(?:\.[A-Za-z]+)*\.\d+\??): (.+)$')
ANY_HEADING = re.compile(r"^#{1,6} ")
REASON_HEADING = re.compile(r"^#{4,5} Reason\s*$")
INTERNAL_LINK = re.compile(r"\[([^\]]+)\]\(#[^)]*\)")
COMMIT = re.compile(r"^\| Commit \| ([0-9a-f]{40}) \|$", re.MULTILINE)


def parse_args():
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    parser.add_argument("--source", type=pathlib.Path, default=BASE / "upstream" / "CppCoreGuidelines.md")
    parser.add_argument("--out", type=pathlib.Path, default=BASE / "sections")
    parser.add_argument("--readme", type=pathlib.Path, default=BASE / "README.md")
    return parser.parse_args()


def split_sections(lines):
    """Return {section id: (title, body lines)} for every top-level section."""
    sections = {}
    current = None
    for line in lines:
        if line.startswith("# "):
            match = SECTION_HEADING.match(line)
            current = match.group(1) if match else None
            if current is not None:
                sections[current] = (match.group(2).strip(), [])
            continue
        if current is not None:
            sections[current][1].append(line)
    return sections


def split_rules(body):
    """Return [(rule id, title, body lines)] in source order."""
    rules = []
    current = None
    for line in body:
        match = RULE_HEADING.match(line)
        if match:
            current = (match.group(1), match.group(2).strip(), [])
            rules.append(current)
        elif line.startswith("## ") or line.startswith("### "):
            current = None
        elif current is not None:
            current[2].append(line)
    return rules


def block(lines, start):
    """Return the lines from start up to the next heading, with outer blank lines removed."""
    end = start
    while end < len(lines) and not ANY_HEADING.match(lines[end]):
        end += 1
    text = []
    for line in lines[start:end]:
        if line.strip() == "???":
            continue  # a placeholder paragraph carries no reason
        if not line.strip() and text and not text[-1].strip():
            continue
        text.append(line)
    while text and not text[0].strip():
        text.pop(0)
    while text and not text[-1].strip():
        text.pop()
    return text


def reason(body):
    """Return the Reason lines of a rule, or its lead text up to the first heading when it has none."""
    for index, line in enumerate(body):
        if REASON_HEADING.match(line):
            return block(body, index + 1)
    return block(body, 0)


def is_stub(text):
    return not "".join(text).replace("?", "").strip()


def clean(line):
    return INTERNAL_LINK.sub(r"\1", line.rstrip())


def render(section_id, title, commit, rules):
    out = [
        f"# {section_id} ({title})",
        "",
        f"Condensed from C++ Core Guidelines commit {commit}: rule id, title and reason only.",
        "Generated by scripts/condense-core-guidelines.py. Do not edit.",
    ]
    for rule_id, rule_title, text in rules:
        out += ["", f"## {rule_id}: {clean(rule_title)}", ""]
        out += [clean(line) for line in text]
    return "\n".join(out) + "\n"


def main():
    args = parse_args()
    match = COMMIT.search(args.readme.read_text(encoding="utf-8"))
    if not match:
        sys.exit(f"{args.readme}: no '| Commit | <sha> |' row")
    commit = match.group(1)

    lines = args.source.read_text(encoding="utf-8").splitlines()
    sections = split_sections(lines)
    missing = [s for s in SECTIONS if s not in sections]
    if missing:
        sys.exit(f"{args.source}: sections not found: {', '.join(missing)}")

    args.out.mkdir(parents=True, exist_ok=True)
    for section_id in SECTIONS:
        title, body = sections[section_id]
        kept, stubs = [], []
        for rule_id, rule_title, rule_body in split_rules(body):
            text = reason(rule_body)
            if is_stub(text):
                stubs.append(rule_id)
            else:
                kept.append((rule_id, rule_title, text))
        path = args.out / f"{section_id}.md"
        path.write_text(render(section_id, title, commit, kept), encoding="utf-8", newline="\n")
        print(f"{section_id}: {len(kept)} rules, {len(stubs)} stubs dropped"
              + (f" ({', '.join(stubs)})" if stubs else ""))


if __name__ == "__main__":
    main()
